pipeline {
    // agent any
    agent {
        docker { image 'node:16-alpine'}
    }

    stages {
        stage('Test-Version') {
            steps {
                script {
                    sh 'node --version'
                }
            }
        }
    }
}