pipeline {
    // agent any
    agent {
        docker { image 'node:16-alpine'}
    }

    stages {
        stage('Test-version') {
            steps {
                sh 'node --version'
            }
        }
    }
}